### ISSUE TITLE
AudioPlayer not playing songs appropriately

### ISSUE THREAD

**Issue by BrianRistau** [BrianRistau/HammerBot#4]
@Moveit56 I am going to delegate this task to you since you have been the one to get this working pretty well in the past.  I'll scan through what you write at the end to make sure that it abides by our current format, but I shouldn't really re-write any of the code.  Thanks!

**Comment by Moveit56** [comment]
There was no SendingHandler being set for the guild that the player is connected in. 

This was resolved by creating a new method in the AudioManager (hammerbot) class which took the parameter of an AudioManager (jda) which was explicit to the current guild that was called in the connect command.

The AudioManager (hammerbot) then set the SendingHandler after using a getPlayer method from the AudioPlayer itself.

Resolved
